### PR TITLE
103 link firebase to local database

### PR DESCRIPTION
**Pull request by Cocograal**
local database synced to the firebase

### CODE REVIEW

**Comment by Bjolidon** [comment]
When exactly does the synchronization occurs? When I launch the app and add cards into my collection, the cards dissapear at the next start of the application (I don't why but we delete the local database each time we start the app). Shouldn't the cards be fetched from the firebase when the local database is deleted?

**Review by Bjolidon — COMMENTED** [review]
Overall the code seems good but the sync is done only when adding or removing card from the collection. Shouldn't we synchronize the databases when the user log in aswell so that the user have access to his collection immediatly when logging on a different phone?

**Comment by Cocograal** [comment]
> Overall the code seems good but the sync is done only when adding or removing card from the collection. Shouldn't we synchronize the databases when the user log in aswell so that the user have access to his collection immediatly when logging on a different phone?

Yes you're right I thought I already did it, but apparently not. Thanks for pointing this out

**Review by Bjolidon — APPROVED** [review]
Thanks for the changes!

**Review by Bjolidon — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
